### ISSUE TITLE
Loop a video in iOS app

### ISSUE THREAD

**Issue by AnujAroshA** [youtube/youtube-ios-player-helper#18]
I am trying to loop a YouTube video in my iOS app. Below is my viewDidLoad method,

- (void)viewDidLoad
{
    [super viewDidLoad];

    self.playerView.delegate = self;

    NSDictionary *playerVars = @{
                                 @"playsinline" : @1,
                                 @"autoplay" : @0,
                                 @"showinfo": @0,
                                 @"controls": @0,
				 @"loop" : @1
                                 };

    [self.playerView loadWithVideoId:selectedYTVideoId playerVars:playerVars];
}

Auto play is working because of following code snippet,

- (void)playerViewDidBecomeReady:(YTPlayerView *)playerView {

    [self.playerView playVideo];    
}

Also I am able to identify when the current video has complete it's playing state like below,

- (void)playerView:(YTPlayerView *)playerView didChangeToState:(YTPlayerState)state{

    if (state == kYTPlayerStateEnded) {
        NSLog(@" Play ended ");
        
    }
}

I want to loop this video. If I put below line after the NSLog statement,

[self.playerView loadWithVideoId:selectedYTVideoId playerVars:playerVars];

the video will loop but before that the view become white. I can reduce the white color appearance for certain extent by editing the "YTPlayerView-iframe-player.html". But I fell that is not the best way to avoid problems with single video looping. Please guide me.

**Comment by delberto91** [comment]
If someone read this post the only thing that you should change this by downloading this library which contains all the necessary to use the youtube api. **pod 'youtube-ios-player-helper', :git =>'https://github.com/youtube/youtube-ios-player-helper', :commit=>'head'** This library contains all the necessary to work with youtube api. You should check in the YTplayerView.m in the line 552 **if ([data isEqual:kYTPlayerStateEndedCode]) {**  you should add below this line of code  **state = kYTPlayerStateEnded;**       because in the library is not evaluating  kYTPlayerStateEnded so you have to add that, after that it will be in the correct way to evaluate this parameter in the way that you want.
