### ISSUE TITLE
Share button is cut in half

### ISSUE THREAD

**Issue by ravigupta049** [youtube/youtube-ios-player-helper#367]
Hi, 
I am having this weird problem with the share button. It started coming as half recently, previously it was working fine. This is happening in both android and iOS helpers. What should I do to resolve it?
<img width="239" alt="Screenshot 2020-03-12 at 6 09 58 PM" src="https://user-images.githubusercontent.com/17566193/76742419-12b81d00-6797-11ea-9487-e51e2421736f.png">

It's coming like this. Any help will be appreciated.

**Comment by HoaDucHung96** [comment]
let playerVars = ["playsinline": 1, "autohide": 1, "showinfo": 1, "controls": 0, "origin" : "http://youtube.com"] as [String : Any]
                let strYoutubeKey = self.extractYoutubeIdFromLink(link: songURL)
                if let strYoutubeKey = strYoutubeKey {
                    DispatchQueue.main.async {
                        self.youtubePlayerView.load(withVideoId: strYoutubeKey, playerVars: playerVars)
                    }
                }

**Comment by HoaDucHung96** [comment]
Please try it

**Comment by todd-patterson** [comment]
Hi ravigupta049,

Thanks for reporting this issue and sorry that we're responding so late. Your screenshot reflects a bug with the underlying YT player (not the "youtube-ios-player-helper" library) that existed from about mid-March until early April. It has since remained fixed, so I'll go ahead and close this ticket.
